apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-worker
  namespace: microservices-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-worker
  template:
    metadata:
      labels:
        app: job-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: job-worker
          image: sandipsamanta/job-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/jobs_db"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: job-worker
  namespace: microservices-monitoring
  labels:
    app: job-worker
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      name: metrics
  selector:
    app: job-worker
