apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-submitter
  namespace: microservices-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-submitter
  template:
    metadata:
      labels:
        app: job-submitter
    spec:
      containers:
        - name: job-submitter
          image: sandipsamanta/job-submitter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/jobs_db"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: job-submitter
  namespace: microservices-monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: job-submitter
